### ISSUE TITLE
allow to abort/TERM (i.e., to press Ctrl-C)

### ISSUE THREAD

**Issue by myrdd** [PotcFdk/youtube-sync#17]
## an example
this is maybe even a special case, because I'm aborting even before the first video has been successfully downloaded.

on commit 8a03b59:

    > youtube-sync setup Foo_Bar 'https://www.youtube.com/user/EckhartTeachings' 
    Set up profile. You can run 'update' on this profile now.

---

    > tree -a SYNC/Foo_Bar/
    SYNC/Foo_Bar/
    └── META
        ├── format
        └── source

    1 directory, 2 files

---

    > youtube-sync update Foo_Bar 
    [youtube:user] FooBar: Downloading channel page
    ^C
    ERROR: Interrupted by user
    find: ‘SYNC/Foo_Bar/ID/’: No such file or directory
    rm: cannot remove 'SYNC/Foo_Bar/LINK/*.mkv': No such file or directory
    /home/myself/bin/youtube-sync: line 126: SYNC/Foo_Bar/META/*.title: No such file or directory
    Creating link: * -> .*.mkv

---

    > tree -a SYNC/Foo_Bar/
    SYNC/Foo_Bar/
    ├── LINK
    │   └── .*.mkv -> ../ID/.mkv
    └── META
        ├── format
        └── source
    
    2 directories, 3 files

**Comment by PotcFdk** [comment]
Sorry for the long silence, should be fixed now. `youtube-sync selfupdate` to update.
