### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Muruxror** [PotcFdk/youtube-sync#20]
Hey,
I guess I'm too stupid to work this out, but how can I get this to work.

I downloaded the script, but the first problem I run into was even getting it to start, no cmd no PowerShell - nothing.

I found noting as good as your script, can somebody help me please.

**Comment by PotcFdk** [comment]
This script is designed for a Unix-like system.
I'm actively developing and testing on the Linux distributions Arch Linux, Debian and Fedora. I expect that Mac OS can be gotten to work somehow, although I don't have any Apple products and cannot test this.
No compatibility with Microsoft environments is expected and no Microsoft shells/interpreters like PowerShell or the Windows Command Processor ("cmd"/cmd.exe) are considered as a target.

**Comment by Muruxror** [comment]
Ok, thx anyways i guess i can work someting out. Btw thank you for the nice and quick response.

Do you want to add something or should i close the request?

**Comment by PotcFdk** [comment]
I don't think much can be done here, so I'll close this issue.
Some quick notes for you, there are ways that one could think about getting this script to work on Windows using some kind of emulation layer. There are some ideas that come to my mind right now:
- WSL (Windows Subsystem for Linux)
- Cygwin
- MSYS(2)
- (Docker ?)
- (Virtual Machines)

While the first four enable you to easily get a bash shell/interpreter on Windows, I am not sure how these systems deal with symlinks on a Windows system. The NTFS filesystem supports symlinks, but access to the relevant OS calls are, as far as I remember, restricted to admin users. I think you'll have to just try out some ideas.
