### ISSUE TITLE
choose to download only audio with youtube-dl settings

### ISSUE THREAD

**Issue by Jarshvor** [PotcFdk/youtube-sync#8]
is this possible as of now?

**Comment by Jarshvor** [comment]
OK, so I just made a copy of the script and modified it. Just removing 'bestvideo' from the 'youtube-dl -i -f bestvideo+bestaudio...' part does quick and dirty fix for me.

Maybe adding an option somewhere to select video quality or only audio would be something useful for some?
Thanks, and closing.

**Comment by myrdd** [comment]
@Jarshvor with PR #9, you will be able to do `echo -n 'bestaudio' > META/format` and youtube-sync will only store the audio.

btw, maybe you also want to change the `--merge-output-format` option to something audio-specific.

**Comment by Jarshvor** [comment]
Thanks @myrdd! Will give this a go when I have a moment.
